trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 
    displayName: Build
    jobs:
    - job: build
      steps:
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/web-app.zip'
            replaceExistingArchive: true

        - publish: $(Build.ArtifactStagingDirectory)
          artifact: web-app 





  - stage: 
    displayName: Deploy to Canary
    jobs:
    - deployment: DEV
      displayName: Deploy to Web App
      environment: DEV
      strategy: 
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: web-app

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'DevopsProjectService'  
                  appType: 'webApp'
                  WebAppName: 'RGATES574717459-Canary'
                  packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
                  enableCustomDeployment: true
                  DeploymentType: 'webDeploy'

  - stage: 
    displayName: Selenium Testing
    jobs:
    - job: selenium_tests
      displayName: Run Selenium Tests
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'

        - script: |
            pip install selenium
          displayName: 'Install Selenium'
                
        - script: |
            pip install webdriver_manager
          displayName: 'Install webdriver_manager'
        
        - script: |
            python st.py
          displayName: 'Run Selenium Tests'


  - stage: 
    displayName: Deploy to Production 
    jobs:
    - deployment: TEST
      displayName: Deploy to Web App
      environment: TEST
      strategy: 
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: web-app

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'DevopsProjectService' 
                  appType: 'webApp'
                  WebAppName: 'RGATES574717459-Prod'
                  packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
                  enableCustomDeployment: true
                  DeploymentType: 'webDeploy'

